### ISSUE TITLE
Callbacks and Error Handling

### ISSUE THREAD

**Issue by edsondearaujo** [edsondearaujo/server-side_Nodejs#5]
## Description
- Study callback function and implement code.

## Tasks
- [x] Understand callback concepts
- [x] Implement callback function
- [x] Handle Error

## Acceptance Criteria
- [x] the system should show an error message, if any.
